comment: false
coverage:
  status:
    patch:
      default:
        informational: true
        target: auto
        threshold: 1.0
    project:
      default:
        informational: true
        target: auto
        threshold: 1.0
codecov:
 token: fcebcc3a-7337-4161-95f1-f23da72a2656
